APP:
  SEED: 1
CORES_AVAILABLE: 20
CURRENT_SET: SET_01
EXPERIMENT_NAME: Ex01_01_minimal_example
POSTPRED:
  LABELS:
  - key: minimal_example
    value: Minimal Example
  LINEAGE_MIN_THRESHOLD: 0.01
  MIN_READ_COUNT: 100
REFERENCES:
  PRIMER_SET: reference/primer_schemes/nCoV-2019_V4/artic_v4.bed
  REF_GENOME: reference/RefSeq_sequence_Wuhan-Hu1.fa
  REF_HUMAN: reference/dummy.fa
SIMULATION:
  AMPLICON_DISTRIBUTION: dirichlet_1
  AMPLICON_PSEUDOCOUNTS: 10
  DATASET:
    SET_01:
      CONSTANT_VARIANT_ABUNDANCE: 0.02
      EXPERIMENT_NO_START: 1
      FORM_PARA:
        growth_rate: 0.2
        init_cases: 1
        max_cases: 1000000
      MAX_TIMEPOINTS: 365
      NAME: minimal_example
      START_DATE: '2023-01-01'
      TIMECOURSE_DATA: ''
      USE_REAL_TIMECOURSE: false
      VARIANTS:
        variant_1:
        - 0
        - B.1.1.7
        variant_2:
        - 30
        - B.1.351
        variant_3:
        - 230
        - B.1.617.2
        variant_4:
        - 128
        - P.1
  N_READS: 100000
  N_SEED: 2
  PRIMER_SET: a4
  QUALITY_SCORES:
  - 400
  - 50
  - 10
  READ_LENGTH: 250
  REFERENCES_SEQUENCES:
  - reference/minimal_example/others.fasta
  - reference/minimal_example/B.1.1.7.fasta
  - reference/minimal_example/B.1.351.fasta
  - reference/minimal_example/B.1.617.2.fasta
  - reference/minimal_example/P.1.fasta
  SAMPLE_COLLECTION:
    NUMBER: 10
    SAMPLE_MODE: even
  SEQ_SYS: MSv3
TOOLS:
  FREYJA_01:
    COLOUR_IN_REPORT: '#65A479FF'
    INCLUDE_IN_ANALYSIS: true
    TOOL_LABEL: Freyja v.2.0.0
    TOOL_NAME: freyja_v2.0.0
  VAQUERO_01:
    COLOUR_IN_REPORT: '#5D8CA8FF'
    DESCRIPTION: current github version
    INCLUDE_IN_ANALYSIS: true
    TOOL_LABEL: VaQuERo v24d9211
    TOOL_NAME: vaquero_v24d9211
  VAQUERO_02:
    COLOUR_IN_REPORT: '#D3BA68FF'
    DESCRIPTION: current github version with old reference set
    INCLUDE_IN_ANALYSIS: false
    TOOL_LABEL: 'VaQuERo v24d9211 oldRef'
    TOOL_NAME: vaquero_v24d9211_oldREF
